### ISSUE TITLE
race condition panic (concurrent map read and map write)

### ISSUE THREAD

**Issue by lun-4** [perk11/large-model-proxy#5]
was running multiple requests against service abc throughout the night, woke up to this

now that we run each request asynchronously in a goroutine (which is good), there is now the possibility of race conditions

could use sync.Mutex, sync.RWMutex, or [syncmap](https://pkg.go.dev/golang.org/x/sync/syncmap), I can make a PR for whichever option would be most prefferable here.

```
2024/08/05 10:28:06 [abc] New client connection received 100.122.23.69:4573->100.73.97.18:36864
2024/08/05 10:28:06 [abc] New client connection received 100.122.23.69:4573->100.73.97.18:36854
fatal error: 2024/08/05 10:28:06 [abc] Opening new service connection to localhost:4973
concurrent map read and map write

goroutine 276567 [running]:
main.startServiceIfNotAlreadyRunningAndConnect({{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, {0xc0001300c0, 0x28}, ...})
        /home/luna/other.git/large-model-proxy/main.go:176 +0x65
main.handleConnection({0x595c98, 0xc000606710}, {{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, ...})
        /home/luna/other.git/large-model-proxy/main.go:156 +0x225
created by main.startProxy in goroutine 37
        /home/luna/other.git/large-model-proxy/main.go:138 +0x537

goroutine 1 [chan receive, 868 minutes]:
main.main()
        /home/luna/other.git/large-model-proxy/main.go:82 +0x43b

goroutine 20 [syscall, 868 minutes]:
os/signal.signal_recv()
        /usr/lib/golang/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
        /usr/lib/golang/src/os/signal/signal.go:151 +0x1f

goroutine 34 [IO wait, 868 minutes]:
internal/poll.runtime_pollWait(0x7f2934d84b68, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xa?, 0x38?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000180100)
        /usr/lib/golang/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000180100)
        /usr/lib/golang/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc0000c6040)
        /usr/lib/golang/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc0000c6040)
        /usr/lib/golang/src/net/tcpsock.go:327 +0x30
main.startProxy({{0xc0001163f0, 0xa}, {0xc0001163fc, 0x4}, {0xc000116400, 0x9}, {0xc00011640c, 0x4}, {0xc000122180, 0x20}, ...})
        /home/luna/other.git/large-model-proxy/main.go:132 +0x2b6
created by main.main in goroutine 1
        /home/luna/other.git/large-model-proxy/main.go:79 +0x2b6

goroutine 35 [IO wait, 868 minutes]:
internal/poll.runtime_pollWait(0x7f2934d84d58, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0x8?, 0x49?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000180000)
        /usr/lib/golang/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000180000)
        /usr/lib/golang/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc0000c6000)
        /usr/lib/golang/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc0000c6000)
        /usr/lib/golang/src/net/tcpsock.go:327 +0x30
main.startProxy({{0xc0001221a0, 0x1b}, {0xc00011641c, 0x4}, {0xc000116430, 0x9}, {0xc00011643c, 0x4}, {0xc0001221c0, 0x20}, ...})
        /home/luna/other.git/large-model-proxy/main.go:132 +0x2b6
created by main.main in goroutine 1
        /home/luna/other.git/large-model-proxy/main.go:79 +0x2b6

goroutine 36 [IO wait, 715 minutes]:
internal/poll.runtime_pollWait(0x7f2934d84c60, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0x9?, 0x3f?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000180080)
        /usr/lib/golang/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc000180080)
        /usr/lib/golang/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc0000c6020)
        /usr/lib/golang/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc0000c6020)
        /usr/lib/golang/src/net/tcpsock.go:327 +0x30
main.startProxy({{0xc000116460, 0xf}, {0xc00011644c, 0x4}, {0xc000116470, 0x9}, {0xc00011647c, 0x4}, {0xc0001221e0, 0x20}, ...})
        /home/luna/other.git/large-model-proxy/main.go:132 +0x2b6
created by main.main in goroutine 1
        /home/luna/other.git/large-model-proxy/main.go:79 +0x2b6

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x7f2934d84e50, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0x3?, 0x3b?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00015c080)
        /usr/lib/golang/src/internal/poll/fd_unix.go:611 +0x2ac
net.(*netFD).accept(0xc00015c080)
        /usr/lib/golang/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc00014a020)
        /usr/lib/golang/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc00014a020)
        /usr/lib/golang/src/net/tcpsock.go:327 +0x30
main.startProxy({{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, {0xc0001300c0, 0x28}, ...})
        /home/luna/other.git/large-model-proxy/main.go:132 +0x2b6
created by main.main in goroutine 1
        /home/luna/other.git/large-model-proxy/main.go:79 +0x2b6

goroutine 276480 [IO wait]:
internal/poll.runtime_pollWait(0x7f2934d20b60, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000124080?, 0xc0006066f0?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.spliceDrain(0xa2, 0xc000124080, 0x100000)
        /usr/lib/golang/src/internal/poll/splice_linux.go:110 +0x22f
internal/poll.Splice(0xc000071f00, 0xc000124080, 0x7fffffffffffffff)
        /usr/lib/golang/src/internal/poll/splice_linux.go:48 +0x173
net.spliceFrom(0x40fb5b?, {0x594920?, 0xc0006066f8?})
        /usr/lib/golang/src/net/splice_linux.go:42 +0x110
net.(*TCPConn).readFrom(0xc0000a24b8, {0x594920, 0xc0006066f8})
        /usr/lib/golang/src/net/tcpsock_posix.go:48 +0x28
net.(*TCPConn).ReadFrom(0xc0000a24b8, {0x594920?, 0xc0006066f8?})
        /usr/lib/golang/src/net/tcpsock.go:130 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a24b8}, {0x594920, 0xc0006066f8}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:415 +0x151
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
net.genericWriteTo(0x7f2934d8b098?, {0x7f2934d8b098, 0xc0000a24b8})
        /usr/lib/golang/src/net/net.go:719 +0x58
net.(*TCPConn).writeTo(0xc0006066f0, {0x7f2934d8b098, 0xc0000a24b8})
        /usr/lib/golang/src/net/tcpsock_posix.go:61 +0x4d
net.(*TCPConn).WriteTo(0xc0006066f0, {0x7f2934d8b098?, 0xc0000a24b8?})
        /usr/lib/golang/src/net/tcpsock.go:142 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a24b8}, {0x594900, 0xc0006066f0}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:411 +0x9d
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
main.copyAndHandleErrors({0x7f2934d8b098?, 0xc0000a24b8?}, {0x594900?, 0xc0006066f0?}, {0xc000284070, 0x6c})
        /home/luna/other.git/large-model-proxy/main.go:506 +0x58
main.forwardConnection({0x595c98, 0xc0000a24b8}, {0x595c98, 0xc0006066f0}, {0xc0001164a0, 0xb})
        /home/luna/other.git/large-model-proxy/main.go:443 +0x4c8
main.handleConnection({0x595c98, 0xc0000a24b8}, {{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, ...})
        /home/luna/other.git/large-model-proxy/main.go:171 +0x406
created by main.startProxy in goroutine 37
        /home/luna/other.git/large-model-proxy/main.go:138 +0x537

goroutine 276566 [IO wait]:
internal/poll.runtime_pollWait(0x7f29342c67e0, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000071f00?, 0x5948c0?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.spliceDrain(0x7c, 0xc000071f00, 0x100000)
        /usr/lib/golang/src/internal/poll/splice_linux.go:110 +0x22f
internal/poll.Splice(0xc000124080, 0xc000071f00, 0x7fffffffffffffff)
        /usr/lib/golang/src/internal/poll/splice_linux.go:48 +0x173
net.spliceFrom(0x595c98?, {0x594920?, 0xc000606700?})
        /usr/lib/golang/src/net/splice_linux.go:42 +0x110
net.(*TCPConn).readFrom(0xc0006066f0, {0x594920, 0xc000606700})
        /usr/lib/golang/src/net/tcpsock_posix.go:48 +0x28
net.(*TCPConn).ReadFrom(0xc0006066f0, {0x594920?, 0xc000606700?})
        /usr/lib/golang/src/net/tcpsock.go:130 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0006066f0}, {0x594920, 0xc000606700}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:415 +0x151
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
net.genericWriteTo(0x7f2934d8b098?, {0x7f2934d8b098, 0xc0006066f0})
        /usr/lib/golang/src/net/net.go:719 +0x58
net.(*TCPConn).writeTo(0xc0000a24b8, {0x7f2934d8b098, 0xc0006066f0})
        /usr/lib/golang/src/net/tcpsock_posix.go:61 +0x4d
net.(*TCPConn).WriteTo(0xc0000a24b8, {0x7f2934d8b098?, 0xc0006066f0?})
        /usr/lib/golang/src/net/tcpsock.go:142 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0006066f0}, {0x594900, 0xc0000a24b8}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:411 +0x9d
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
main.copyAndHandleErrors({0x7f2934d8b098?, 0xc0006066f0?}, {0x594900?, 0xc0000a24b8?}, {0xc00017ff80, 0x6c})
        /home/luna/other.git/large-model-proxy/main.go:506 +0x58
created by main.forwardConnection in goroutine 276480
        /home/luna/other.git/large-model-proxy/main.go:438 +0x358

goroutine 11193 [IO wait, 722 minutes]:
internal/poll.runtime_pollWait(0x7f2934d84880, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000070580?, 0x3d?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.spliceDrain(0x3e, 0xc000070580, 0x100000)
        /usr/lib/golang/src/internal/poll/splice_linux.go:110 +0x22f
internal/poll.Splice(0xc000070480, 0xc000070580, 0x7fffffffffffffff)
        /usr/lib/golang/src/internal/poll/splice_linux.go:48 +0x173
net.spliceFrom(0x40fb5b?, {0x594920?, 0xc000408010?})
        /usr/lib/golang/src/net/splice_linux.go:42 +0x110
net.(*TCPConn).readFrom(0xc0000a2118, {0x594920, 0xc000408010})
        /usr/lib/golang/src/net/tcpsock_posix.go:48 +0x28
net.(*TCPConn).ReadFrom(0xc0000a2118, {0x594920?, 0xc000408010?})
        /usr/lib/golang/src/net/tcpsock.go:130 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a2118}, {0x594920, 0xc000408010}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:415 +0x151
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
net.genericWriteTo(0x7f2934d8b098?, {0x7f2934d8b098, 0xc0000a2118})
        /usr/lib/golang/src/net/net.go:719 +0x58
net.(*TCPConn).writeTo(0xc000408008, {0x7f2934d8b098, 0xc0000a2118})
        /usr/lib/golang/src/net/tcpsock_posix.go:61 +0x4d
net.(*TCPConn).WriteTo(0xc000408008, {0x7f2934d8b098?, 0xc0000a2118?})
        /usr/lib/golang/src/net/tcpsock.go:142 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a2118}, {0x594900, 0xc000408008}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:411 +0x9d
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
main.copyAndHandleErrors({0x7f2934d8b098?, 0xc0000a2118?}, {0x594900?, 0xc000408008?}, {0xc000140070, 0x6c})
        /home/luna/other.git/large-model-proxy/main.go:506 +0x58
main.forwardConnection({0x595c98, 0xc0000a2118}, {0x595c98, 0xc000408008}, {0xc0001164a0, 0xb})
        /home/luna/other.git/large-model-proxy/main.go:443 +0x4c8
main.handleConnection({0x595c98, 0xc0000a2118}, {{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, ...})
        /home/luna/other.git/large-model-proxy/main.go:171 +0x406
created by main.startProxy in goroutine 37
        /home/luna/other.git/large-model-proxy/main.go:138 +0x537

goroutine 276568 [runnable]:
net.(*Resolver).lookupIPAddr(0x66eb80, {0x5951f0, 0x6ce7a0}, {0x55dd37, 0x3}, {0xc000015c60, 0x9})
        /usr/lib/golang/src/net/lookup.go:304 +0xcd8
net.(*Resolver).internetAddrList(0x66eb80?, {0x5951f0?, 0x6ce7a0?}, {0x55dd37, 0x3}, {0xc000015c60?, 0x53?})
        /usr/lib/golang/src/net/ipsock.go:288 +0x4d9
net.(*Resolver).resolveAddrList(0x66eb80, {0x5951f0, 0x6ce7a0}, {0x55de3e, 0x4}, {0x55dd37?, 0x0?}, {0xc000015c60, 0xe}, {0x0, ...})
        /usr/lib/golang/src/net/dial.go:283 +0x3e5
net.(*Dialer).DialContext(0xc0002b1938, {0x5951f0, 0x6ce7a0}, {0x55dd37, 0x3}, {0xc000015c60, 0xe})
        /usr/lib/golang/src/net/dial.go:490 +0x405
net.(*Dialer).Dial(...)
        /usr/lib/golang/src/net/dial.go:434
net.Dial({0x55dd37?, 0xc0001164b0?}, {0xc000015c60?, 0x592af8?})
        /usr/lib/golang/src/net/dial.go:401 +0x77
main.connectToService({{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, {0xc0001300c0, 0x28}, ...})
        /home/luna/other.git/large-model-proxy/main.go:253 +0x23c
main.startServiceIfNotAlreadyRunningAndConnect({{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, {0xc0001300c0, 0x28}, ...})
        /home/luna/other.git/large-model-proxy/main.go:194 +0x218
main.handleConnection({0x595c98, 0xc000606718}, {{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, ...})
        /home/luna/other.git/large-model-proxy/main.go:156 +0x225
created by main.startProxy in goroutine 37
        /home/luna/other.git/large-model-proxy/main.go:138 +0x537

goroutine 276526 [IO wait]:
internal/poll.runtime_pollWait(0x7f2934d220b0, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00015d300?, 0xc0006066e0?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.spliceDrain(0x80, 0xc00015d300, 0x100000)
        /usr/lib/golang/src/internal/poll/splice_linux.go:110 +0x22f
internal/poll.Splice(0xc00015d200, 0xc00015d300, 0x7fffffffffffffff)
        /usr/lib/golang/src/internal/poll/splice_linux.go:48 +0x173
net.spliceFrom(0x40fb5b?, {0x594920?, 0xc0006066e8?})
        /usr/lib/golang/src/net/splice_linux.go:42 +0x110
net.(*TCPConn).readFrom(0xc0006066c0, {0x594920, 0xc0006066e8})
        /usr/lib/golang/src/net/tcpsock_posix.go:48 +0x28
net.(*TCPConn).ReadFrom(0xc0006066c0, {0x594920?, 0xc0006066e8?})
        /usr/lib/golang/src/net/tcpsock.go:130 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0006066c0}, {0x594920, 0xc0006066e8}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:415 +0x151
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
net.genericWriteTo(0x7f2934d8b098?, {0x7f2934d8b098, 0xc0006066c0})
        /usr/lib/golang/src/net/net.go:719 +0x58
net.(*TCPConn).writeTo(0xc0006066e0, {0x7f2934d8b098, 0xc0006066c0})
        /usr/lib/golang/src/net/tcpsock_posix.go:61 +0x4d
net.(*TCPConn).WriteTo(0xc0006066e0, {0x7f2934d8b098?, 0xc0006066c0?})
        /usr/lib/golang/src/net/tcpsock.go:142 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0006066c0}, {0x594900, 0xc0006066e0}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:411 +0x9d
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
main.copyAndHandleErrors({0x7f2934d8b098?, 0xc0006066c0?}, {0x594900?, 0xc0006066e0?}, {0xc00017ff10, 0x6c})
        /home/luna/other.git/large-model-proxy/main.go:506 +0x58
main.forwardConnection({0x595c98, 0xc0006066c0}, {0x595c98, 0xc0006066e0}, {0xc0001164a0, 0xb})
        /home/luna/other.git/large-model-proxy/main.go:443 +0x4c8
main.handleConnection({0x595c98, 0xc0006066c0}, {{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, ...})
        /home/luna/other.git/large-model-proxy/main.go:171 +0x406
created by main.startProxy in goroutine 37
        /home/luna/other.git/large-model-proxy/main.go:138 +0x537

goroutine 276590 [IO wait]:
internal/poll.runtime_pollWait(0x7f2934d444a0, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000124100?, 0x1?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.spliceDrain(0x46, 0xc000124100, 0x100000)
        /usr/lib/golang/src/internal/poll/splice_linux.go:110 +0x22f
internal/poll.Splice(0xc000124200, 0xc000124100, 0x7fffffffffffffff)
        /usr/lib/golang/src/internal/poll/splice_linux.go:48 +0x173
net.spliceFrom(0x50e905?, {0x594920?, 0xc000606708?})
        /usr/lib/golang/src/net/splice_linux.go:42 +0x110
net.(*TCPConn).readFrom(0xc0000a24f8, {0x594920, 0xc000606708})
        /usr/lib/golang/src/net/tcpsock_posix.go:48 +0x28
net.(*TCPConn).ReadFrom(0xc0000a24f8, {0x594920?, 0xc000606708?})
        /usr/lib/golang/src/net/tcpsock.go:130 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a24f8}, {0x594920, 0xc000606708}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:415 +0x151
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
net.genericWriteTo(0x7f2934d8b098?, {0x7f2934d8b098, 0xc0000a24f8})
        /usr/lib/golang/src/net/net.go:719 +0x58
net.(*TCPConn).writeTo(0xc0000a24d8, {0x7f2934d8b098, 0xc0000a24f8})
        /usr/lib/golang/src/net/tcpsock_posix.go:61 +0x4d
net.(*TCPConn).WriteTo(0xc0000a24d8, {0x7f2934d8b098?, 0xc0000a24f8?})
        /usr/lib/golang/src/net/tcpsock.go:142 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a24f8}, {0x594900, 0xc0000a24d8}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:411 +0x9d
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
main.copyAndHandleErrors({0x7f2934d8b098?, 0xc0000a24f8?}, {0x594900?, 0xc0000a24d8?}, {0xc0001412d0, 0x6c})
        /home/luna/other.git/large-model-proxy/main.go:506 +0x58
created by main.forwardConnection in goroutine 276583
        /home/luna/other.git/large-model-proxy/main.go:438 +0x358

goroutine 276583 [IO wait]:
internal/poll.runtime_pollWait(0x7f2934cc64b0, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc000124200?, 0xc0002144e0?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.spliceDrain(0x2c, 0xc000124200, 0x100000)
        /usr/lib/golang/src/internal/poll/splice_linux.go:110 +0x22f
internal/poll.Splice(0xc000124100, 0xc000124200, 0x7fffffffffffffff)
        /usr/lib/golang/src/internal/poll/splice_linux.go:48 +0x173
net.spliceFrom(0x40fb5b?, {0x594920?, 0xc0000a2500?})
        /usr/lib/golang/src/net/splice_linux.go:42 +0x110
net.(*TCPConn).readFrom(0xc0000a24d8, {0x594920, 0xc0000a2500})
        /usr/lib/golang/src/net/tcpsock_posix.go:48 +0x28
net.(*TCPConn).ReadFrom(0xc0000a24d8, {0x594920?, 0xc0000a2500?})
        /usr/lib/golang/src/net/tcpsock.go:130 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a24d8}, {0x594920, 0xc0000a2500}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:415 +0x151
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
net.genericWriteTo(0x7f2934d8b098?, {0x7f2934d8b098, 0xc0000a24d8})
        /usr/lib/golang/src/net/net.go:719 +0x58
net.(*TCPConn).writeTo(0xc0000a24f8, {0x7f2934d8b098, 0xc0000a24d8})
        /usr/lib/golang/src/net/tcpsock_posix.go:61 +0x4d
net.(*TCPConn).WriteTo(0xc0000a24f8, {0x7f2934d8b098?, 0xc0000a24d8?})
        /usr/lib/golang/src/net/tcpsock.go:142 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0000a24d8}, {0x594900, 0xc0000a24f8}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:411 +0x9d
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
main.copyAndHandleErrors({0x7f2934d8b098?, 0xc0000a24d8?}, {0x594900?, 0xc0000a24f8?}, {0xc000141340, 0x6c})
        /home/luna/other.git/large-model-proxy/main.go:506 +0x58
main.forwardConnection({0x595c98, 0xc0000a24d8}, {0x595c98, 0xc0000a24f8}, {0xc0001164a0, 0xb})
        /home/luna/other.git/large-model-proxy/main.go:443 +0x4c8
main.handleConnection({0x595c98, 0xc0000a24d8}, {{0xc0001164a0, 0xb}, {0xc00011648c, 0x4}, {0xc0001164b0, 0x9}, {0xc0001164bc, 0x4}, ...})
        /home/luna/other.git/large-model-proxy/main.go:171 +0x406
created by main.startProxy in goroutine 37
        /home/luna/other.git/large-model-proxy/main.go:138 +0x537

goroutine 276565 [IO wait]:
internal/poll.runtime_pollWait(0x7f2934cc63b8, 0x72)
        /usr/lib/golang/src/runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00015d200?, 0x1?, 0x0)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.spliceDrain(0x7a, 0xc00015d200, 0x100000)
        /usr/lib/golang/src/internal/poll/splice_linux.go:110 +0x22f
internal/poll.Splice(0xc00015d300, 0xc00015d200, 0x7fffffffffffffff)
        /usr/lib/golang/src/internal/poll/splice_linux.go:48 +0x173
net.spliceFrom(0x50e905?, {0x594920?, 0xc0000a24b0?})
        /usr/lib/golang/src/net/splice_linux.go:42 +0x110
net.(*TCPConn).readFrom(0xc0006066e0, {0x594920, 0xc0000a24b0})
        /usr/lib/golang/src/net/tcpsock_posix.go:48 +0x28
net.(*TCPConn).ReadFrom(0xc0006066e0, {0x594920?, 0xc0000a24b0?})
        /usr/lib/golang/src/net/tcpsock.go:130 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0006066e0}, {0x594920, 0xc0000a24b0}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:415 +0x151
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
net.genericWriteTo(0x7f2934d8b098?, {0x7f2934d8b098, 0xc0006066e0})
        /usr/lib/golang/src/net/net.go:719 +0x58
net.(*TCPConn).writeTo(0xc0006066c0, {0x7f2934d8b098, 0xc0006066e0})
        /usr/lib/golang/src/net/tcpsock_posix.go:61 +0x4d
net.(*TCPConn).WriteTo(0xc0006066c0, {0x7f2934d8b098?, 0xc0006066e0?})
        /usr/lib/golang/src/net/tcpsock.go:142 +0x30
io.copyBuffer({0x7f2934d8b098, 0xc0006066e0}, {0x594900, 0xc0006066c0}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:411 +0x9d
io.Copy(...)
        /usr/lib/golang/src/io/io.go:388
main.copyAndHandleErrors({0x7f2934d8b098?, 0xc0006066e0?}, {0x594900?, 0xc0006066c0?}, {0xc00017fea0, 0x6c})
        /home/luna/other.git/large-model-proxy/main.go:506 +0x58
created by main.forwardConnection in goroutine 276526
        /home/luna/other.git/large-model-proxy/main.go:438 +0x358
exit status 2
```

**Comment by perk11** [comment]
I also noticed this issue. sync. Mutex is already used in other places, so I'd prefer to stick with that. If you want to dig to see where the missing spot is and submit a PR, please feel free. I was going to try to fix this, but might not have time for the next few days.

I plan to write some automated tests for the server to be able to catch issues like this more easily in the future.
